# NumPy Arrays:
1. **Vectors and Matrices**
    
    import numpy as np
    
    np.array(arg) => arg is a list which is converted to single dimensional array i.e. vector 
    
    or 2 dimensions array if it is a list of list. 
    
    The number of square brackets at the start and the end indicate the dimension of the array.
    
    
2. **Generation Functions**

    2.1 **arange** ==> np.arange(start,stop, step) // function to generate arrange from start until stop with given step size
   
    2.2 **zeros** ==> np.zeros(size) // function to generate single or 2 dimensinal array initialized to 0
   
      // size = single number or a tuple
   
    2.3 **ones** ==> np.ones(size) // function to generate single or 2 dimensinal array initialized to 1.0
   
      // size = single number or a tuple
     
    2.4 **linspace** ==> np.linspace(start,stop,numpoints) 
    
      // generates a single dimensional vectors with numpoints evenly spaced points between start to stop
    
    2.5 **eye** ==> np.eye(size) // identity matrix creation function i.e. element(i,i)= 1.0, 
    
      // single argument is taken as the input as the identity matrix is always square matrix i.e. #rows = #columns
    
    2.6 **random** ==> create arrays of random numbers
    
         2.6.1 np.random.rand(dimension) => create an array of given dimension with random numbers 
         from uniform distribution from 0 to 1
    
         2.6.2.np.random.rand(dimension,dimension)=> create an 2-D array of given dimension with random numbers 
         from uniform distribution from 0 to 1
    
         2.6.3.np.random.rand**n**(dimension) => create an array of given dimension with random numbers 
         from standard distribution centered around 0
     
         2.6.4.np.random.rand**n**(dimension,dimension)=> create an 2-D array of given dimension with random numbers 
         from standard distribution centered around 0
            
         2.6.5.np.random.randint(low,high,size)=> create an 2-D array of given dimension with random integers 
         from low upto high of given size
    
   2.7 **reshape** ==> reshape the array of given size 
    
     array.reshape(row,columns) // number of elements should be enough to completely fill the new size 
    
     //i.e. row * columns = oldsize
      
   2.8 **Find max or min values** ==> functions to find max or min values and return the index locations
        
        2.8.1 rarray.max() ==> functions to find max element in array
      
        2.8.2 rarray.min() ==> functions to find min element in array
      
        2.8.3 rarray.argmax() ==> functions to find max element index in array 
    
        2.8.4 rarray.argmin() ==> functions to find min element index in array 

   2.9 **Find shape of the vector** ==> attribute to find the shape of the vector
    
     array.shape ==> returns the shape of the array
      
   3.0 **Find datatype in the array** ==> find datatype of the elements of the array
    
     array.dtype ==>returns dtype(type)
      
      
3. **Importing specific functions from the lib**
 
    from numpy.random import randint 
    
    randint(2,10)
    

In [1]:
mylist=[1,2,3,4]
mylist

[1, 2, 3, 4]

In [2]:
import numpy as np
np.array(mylist)


array([1, 2, 3, 4])

In [3]:
my_mat= [[1,2,3],[4,5,6,],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
 np.random.rand(3,3)

array([[0.99118174, 0.93719251, 0.44172127],
       [0.01518659, 0.24849966, 0.29202744],
       [0.24112227, 0.97170089, 0.56250282]])

In [18]:
array = np.arange(25)
array
rarray= np.random.randint(0,50,10)
rarray
array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
rarray

array([24, 33, 27, 33, 24, 20, 33, 44, 48, 12])

In [20]:
rarray.max()

48

# NumPy Indexing and Selection

1. Indexing used to get the element from the array 

2. Slice notation works for getting the subarray from the array arra[m:n]

3. Slicing creates reference to original array from the array to which the slice is assigned. So if the elements of the sliced array are broadcasted to another value i.e. new value assigned to sliced array, then original array elements are reassigned as well. 
    
    import numpy as np
    
    arr = np.arange(0,10)
    
    arr[1:6]
    
    slice_of_array = arr[1:6]
    
    slice_of_array[:6] =  10
    
    arr[1:6] 
    
   
4. To create a real copy of the array, .copy() method of the array class. 
    
    Copy_of_array = arr.copy()
    
    Copy_of_array[:6] =  0
    
    arr[1:6] 
    
    Copy_of_array[1:6]
    

5. Indexing 2d array

    array_2d =np.array([[1,2,3],[4,5,6],[7,8,9]])
    
    array_2d
    
    array_2d[0] //entire row
    
    array_2d[1][0] // row =1, column =0 element
    
    array_2d[1,0] // row =1, column =0 element 
    

7. Grabbing multiple rows and columns from np 2D array using Slice notation

    array_2d[:2,1:] // get all the rows upto 2nd row and all the column starting from 1 upto the end  
    
    array_2d[1:,:2] // get all the rows from 1st row and all the column starting upto 2nd
    
 
8. Comparison operator on the array elements

   array_com = np.arange(0,9)
   array_com
   
   array_com > 10
   
   Returns the array of boolean value with result of the comparison for each element of the array 
   
   array([False, False, False, False, False, False, False, False, False])
   
    
9. Using comparison operator for choosing selectively the elements of the array
    
    array_com = np.arange(0,9)
    
    bool_array = array_com > 1
    
    array_com[bool_array] **OR**   array_com[array_com > 2]
    
    

In [13]:
    import numpy as np
    arr = np.arange(0,10)
    arr[1:6]
    slice_of_array = arr[1:6]
    slice_of_array[:6] =  10
    arr[1:6] 

array([10, 10, 10, 10, 10])

In [14]:
Copy_of_array = arr.copy()
Copy_of_array[:6] =  0
arr[1:6] 

array([10, 10, 10, 10, 10])

In [15]:
Copy_of_array[1:6]

array([0, 0, 0, 0, 0])

In [17]:
array_2d =[[1,2,3],[4,5,6],[7,8,9]] 
array_2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
array_2d =np.array([[1,2,3],[4,5,6],[7,8,9]]) 

In [19]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
array_2d[0]

array([1, 2, 3])

In [22]:
array_2d[1,0]

4

In [23]:
array_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [24]:
array_2d[1:,:2]

array([[4, 5],
       [7, 8]])

In [25]:
array_2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [29]:
array_com = np.arange(0,9)
array_com

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
array_com > 10

array([False, False, False, False, False, False, False, False, False])

In [32]:
array_com = np.arange(0,9)
bool_array = array_com > 1
array_com[bool_array]

array([2, 3, 4, 5, 6, 7, 8])

In [33]:
array_com[array_com > 2]

array([3, 4, 5, 6, 7, 8])

# NumPy Operations 

1. **Array with Array**
   
       1.1. Adding two arrays: 
        
            arr= np.arange(0,10)
            
            arr = arr + arr // arr[i] + arr[i] for each element i in the array 
   
       1.2 Subtracting two arrays:
       
            arr = arr - arr // arr[i] - arr[i] for each element i in the array 
    
       1.3 Multiplying two arrays: 
   
            arr = arr * arr // arr[i] * arr[i] for each element i in the array 
   
       1.4 Exponents two arrays: 
   
            arr = arr ** arr // arr[i] ** arr[i] for each element i in the array
            
           
2. **Array with Scalars**

       2.1. Adding scalar to an arrays: 
        
            arr= np.arange(0,10)
            
            arr = arr + 100 // arr[i] + 100 for each element i in the array 
   
       2.2 Subtracting scalar from  arrays:
       
            arr = arr - 100 // arr[i] - 100 for each element i in the array 
    
       2.3 Multiplying scalar to arrays: 
   
            arr = arr * 100 // arr[i] * 100 for each element i in the array   
          
       2.4 Exponents scalar to arrays: 
   
            arr = arr ** 100 // arr[i] ** 100 for each element i in the array

3. **Universal Array Functions**

       3.1 sin()
       
       3.2 max()
       
       3.3 min()
       
       3.4 exp()
       .
       .
       .
       

In [3]:
import numpy as np
arr= np.arange(0,10)
arr = arr + arr
arr


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr = arr - arr
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
arr = arr * arr
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr = arr + 100
arr

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])